# Site settings
title: Bank Pracy - Wolontariusze ŚDM
facebook: "facebook.com/swiatowydzienmlodziezy"
description: "Jeżeli chcesz się zaangażować w organizację ŚDM - zgłoś chęć wykonania konkretnego zadania!"
baseurl: "/jobs"
url: "https://krakow2016.github.io"
backend: "http://infinite-everglades-3721.herokuapp.com"
twitter_username: "sdm_pl"
github_username: "Krakow2016"

# Build settings
markdown: kramdown
permalink: pretty
