# Site settings
title: Bank Pracy - Wolontariusze ŚDM
facebook: "facebook.com/swiatowydzienmlodziezy"
description: "Jeżeli chcesz się zaangażować w organizację ŚDM - zgłoś chęć wykonania konkretnego zadania!"
baseurl: "/tablica"
url: "https://krakow2016.github.io"
backend: "http://infinite-everglades-3721.herokuapp.com"
twitter_username: "sdm_pl"
github_username: "Krakow2016"

# Build settings
markdown: kramdown
permalink: "/:title.html"

prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - _config.yml
    - /_layouts
    - /_includes
    - README.markdown
    - .gitignore
    - feed.xml
    - robots.txt
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: true
      - name: "title"
        field:
          element: "text"
          label: "Tytuł"
          value: ""
      - name: "categories"
        field:
          element: "multiselect"
          label: "Dodaj kategorię"
          placeholder: "Wybierz kategorię"
          alterable: true
          options:
            - name: "Wolontariat"
              value: "wolontariat"
            - name: "Grafika"
              value: "grafika"
      - name: "team_count"
        field:
          element: "text"
          label: "Liczba osób potrzebna do wykonania zadania"
          value: "1"
      - name: "archive"
        field:
          element: "checkbox"
          label: "Archiwum"
          value: false
